In [1]:
import numpy as np

In [13]:
class NerualNetwork:
    
    def __init__(self,inputNodes,hiddenNodes,outputNodes,learningRate):
        self.inodes = inputNodes
        self.hnodes = hiddenNodes
        self.onodes = outputNodes
        
        self.ihw = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes)) #(numpy.random.rand(self.hnodes, self.inodes) - 0.5)
        self.how = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes)) #(numpy.random.rand(self.onodes, self.hnodes) - 0.5) 
        self.lr = learningRate
        
        pass
    def train():
        pass
    def query():
        pass

In [14]:
inputNodes = 3
hiddenNodes = 3
outputNodes = 3

learningRate = 0.3

NN = NerualNetwork(inputNodes,hiddenNodes,outputNodes,learningRate)

In [23]:
print("Input Nodes: {} , Hidden Nodes: {}, Output Nodes: {} , Learning Rate: {} \n".format(NN.inodes,NN.hnodes,NN.onodes,NN.lr))
print("Input to Hidden Connection Matrix: \n {} \n\n Hidden to Output Connection Matrix: \n {}".format(NN.ihw,NN.how))

Input Nodes: 3 , Hidden Nodes: 3, Output Nodes: 3 , Learning Rate: 0.3 

Input to Hidden Connection Matrix: 
 [[ 1.09183856 -0.59326463 -0.5820006 ]
 [ 0.46321013  0.79077273  0.23028538]
 [-0.38560366 -0.34995266 -0.63524125]] 

 Hidden to Output Connection Matrix: 
 [[-0.72528771 -0.89543456  0.42825826]
 [ 0.13336004 -0.18022436 -0.35442224]
 [-0.32354437 -0.67921183 -0.20800705]]
