In [2]:
import numpy as np

In [4]:
pow(4,-0.5)

0.5

In [9]:
ah = np.random.normal(0.0, pow(3, -0.5), (3,3))

In [11]:
ah

array([[-0.34350216, -0.47985233, -0.33977355],
       [-0.38768843, -0.01936744,  0.40615715],
       [-0.51963781, -0.02349786,  0.24848727]])

In [12]:
ah[0]

array([-0.34350216, -0.47985233, -0.33977355])

In [13]:
ah[1]

array([-0.38768843, -0.01936744,  0.40615715])

In [14]:
ah[2]

array([-0.51963781, -0.02349786,  0.24848727])

In [16]:
ah.size

9

In [17]:
ah.shape

(3, 3)

In [18]:
type(ah)

numpy.ndarray

In [19]:
ab = np.random.normal(0.0, pow(3, -0.5), (3,3))

In [20]:
ab[0]

array([ 0.22565425, -0.12194191,  0.25352769])

In [21]:
ab[1]

array([-0.54580547, -0.18225674, -0.30569506])

In [22]:
ab[2]

array([ 0.98467594,  0.33100764, -1.34358087])

In [23]:
ab.size

9

In [24]:
ab.shape

(3, 3)

In [26]:
a = ab * ah

In [28]:
a[0][0]

-0.07751272274292804

In [29]:
ab[0][0] * ah[0][0]

-0.07751272274292804

In [30]:
np.dot(ah,ab) #dot product 

array([[-0.15017353,  0.01687599,  0.51611442],
       [ 0.32302048,  0.18524643, -0.6380742 ],
       [ 0.14024621,  0.14989945, -0.45842214]])

In [32]:
(ah[0][0] * ab[0][0]) + (ah[0][1] * ab[1][0]) + (ah[0][2] * ab[2][0]) #entry[0][0] of dot product row * colum

-0.15017352633280961

In [17]:
inputs = np.array(np.random.normal(0.0, pow(3, -0.5), (3,3)), ndmin=2).T

In [18]:
inputs

array([[-0.03444404, -0.2795893 , -1.20004239],
       [-0.66505314,  0.38614331, -0.42474933],
       [ 1.15692536, -0.07755581, -0.20496758]])

In [22]:
l = list()

TypeError: 'int' object is not iterable

In [20]:
l[2] = 1

IndexError: list assignment index out of range